// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1BYou8Wf7-ipg8T6X_dYgurNxVfS1Vw',
    appId: '1:8499183989:web:ec36386543e3a667d6933c',
    messagingSenderId: '8499183989',
    projectId: 'fir-2f9e5',
    authDomain: 'fir-2f9e5.firebaseapp.com',
    databaseURL:
        'https://fir-2f9e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2f9e5.appspot.com',
    measurementId: 'G-3NLZ4820G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMr2bqOB5AjBYU3VvQpjWeN-McXpv_7es',
    appId: '1:8499183989:android:b7be853eb5099fb2d6933c',
    messagingSenderId: '8499183989',
    projectId: 'fir-2f9e5',
    databaseURL:
        'https://fir-2f9e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2f9e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP6qUdogzG348uREIhvshkII4YzCIurEg',
    appId: '1:8499183989:ios:928a81678fafd712d6933c',
    messagingSenderId: '8499183989',
    projectId: 'fir-2f9e5',
    databaseURL:
        'https://fir-2f9e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2f9e5.appspot.com',
    iosClientId:
        '8499183989-pq6ugt54a27kc5ecc0rt6siusd1hkqcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP6qUdogzG348uREIhvshkII4YzCIurEg',
    appId: '1:8499183989:ios:908534d769383d91d6933c',
    messagingSenderId: '8499183989',
    projectId: 'fir-2f9e5',
    databaseURL:
        'https://fir-2f9e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2f9e5.appspot.com',
    iosClientId:
        '8499183989-8i3tjuak4invu7ghn4jn45c4ekhupdsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication0.RunnerTests',
  );
}
